- name: Install required packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-pymysql
    state: present
    update_cache: yes

- name: Install Flask and PyMySQL
  shell: pip3 install flask pymysql

- name: Deploy Flask app from template
  template:
    src: app.py.j2
    dest: /home/ubuntu/app.py
    mode: '0644'

- name: Kill existing Flask app
  shell: pkill -f app.py || true

- name: Start Flask app
  shell: nohup python3 /home/ubuntu/app.py > /home/ubuntu/flask.log 2>&1 &

- name: Wait for Flask app to start
  pause:
    seconds: 5

- name: Check Flask app is running
  shell: ps aux | grep app.py | grep -v grep
  register: flask_process
  failed_when: flask_process.stdout == ""